version: "3"
services:
  mongodbcontainer:
    image: mongo:latest
    container_name: mongodbcontainer
    ports:
      - "27017:27017"

  logingestordocker:
    image: logingestordocker:1.0
    container_name: logingestordocker
    ports:
      - "3000:3000"
    depends_on:
      - mongodbcontainer
    links:
      - mongodbcontainer